version: "1"
services:
  # Add your containers here, specifying the base image you want to build from
  # For example:
  #
  python_image:
     image: ubuntu:trusty
     dev_overrides:
       environment:
         - "DEBUG=1"
registries: {}
  # Add optional registries used for deployment. For example:
  #  google:
  #    url: https://gcr.io
  #    namespace: my-cool-project-xxxxxx
